AWSTemplateFormatVersion: 2010-09-09
Description: Skeleton for CodePipeline CI/CD pipeline

# Parameters:
  # GitHubOAuthToken:
  #   Type: String
  #   NoEcho: true
  #   MinLength: 40
  #   MaxLength: 40
  #   AllowedPattern: "[a-z0-9]*"

  # GitHubOwner:
  #   Type: String
  #   Default: claudioscheer
  #   AllowedPattern: "[A-Za-z0-9-]+"

  # GitHubRepo:
  #   Type: String
  #   Default: codepipeline-skeleton
  #   AllowedPattern: "[A-Za-z0-9-]+"

  # GitHubBranch:
  #   Type: String
  #   Default: master
  #   AllowedPattern: "[A-Za-z0-9-]+"
